# -*- coding: utf-8 -*-
"""01_CF_EDA.ipynb

Automatically generated by Colab.

# Preparation
"""

import pandas as pd
import numpy as np
import json
import re
import joblib

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
from matplotlib import rcParams

rcParams['figure.figsize'] = 15, 8
mpl.style.use(['ggplot'])

# Read the JSON files
with open('cf21-catalog.json', 'r') as f:
    df_21 = pd.DataFrame(json.load(f))
    df_21['CF_Version'] = 21

with open('cf22-catalog.json', 'r') as f:
    df_22 = pd.DataFrame(json.load(f))
    df_22['CF_Version'] = 22

# Data Processing for CF22 (replace \u002F with /)
# Use a more robust check to handle columns containing lists/arrays
for col in df_22.columns:
    if df_22[col].dtype == object:
        df_22[col] = df_22[col].apply(lambda x: str(x).replace('\\u002F', '/') if pd.api.types.is_scalar(x) and pd.notnull(x) else x)

# Combine datasets into one dataframe
df_cf = pd.concat([df_21, df_22], ignore_index=True)

"""# Fandom"""

# Define all target keywords
hoyoverse_keywords = [
    "hoyo", "hoyoverse", "mihoyo",
    "genshin impact", "genshin", "gensin", "genshininpact",
    "honkai", "honkai star rail", "hsr", "honkai: star rail", "honkaistarrail", "honkaistarrail", "honkaistarrails",
    "honkai impact", "hi3", "honkaiimpact",
    "zzz", "zenless zone zero", "zenlesszonezero", "zenless", "star rail", "starrail"
]

vtuber_keywords = [
    "vtuber", "virtual youtuber", "hololive", "nijisanji", "vshojo", "v-tuber"
]

gacha_keywords = [
    "arknight", "arknights", "blue archive", "bluearchive", "blue archieve",
    "reverse 1999", "reverse1999", "reverse:1999", "wuthering wave", "wuthering waves", "wuwa",
    "pgr", "punishing gray raven", "punishing grey raven",
    "love and deepspace", "love & deepspace", "limbus company", "limbuscompany",
    "aether gazer", "aethergazer", "fgo", "fate grand order", "fate/grand order",
    "nikke", "goddess of victory", "uma musume", "umamusume",
    "endfield", "azur lane", "azurlane", "neverness to everness", "nte", "lads", "lad", "azur"
]

vsynth_keywords = [
    "vocaloid", "hatsune miku", "miku", "project sekai", "prosekai", "prsk",
    "utau", "kasane teto", "kagamine", "rin len", "megurine luka", "kaito", "meiko",
    "gumi", "cevio", "synthesizer v", "synthv", "vvoice synth", "pjsk", "proseka"
]

original_keywords = [
    "original", "original work", "original works", "original art",
    "original ip", "original character", "originals", "original design", "oc"
]

# Function to check for keyword presence in a string (case-insensitive and allowing for slight variations)
def contains_keyword(fandom_text, keywords, is_exact_oc=False):
    if pd.isna(fandom_text):
        return False
    text = str(fandom_text).lower()
    for keyword in keywords:
        if keyword == "oc" and is_exact_oc:
            pattern = r'\boc\b'
        else:
            pattern = r'\s*'.join(re.escape(word) for word in keyword.split())
        if re.search(pattern, text):
            return True
    return False

# Apply unified mappings
def categorize_booth(row):
    fandom = row['fandom']
    other_fandom = row.get('other_fandom', '')

    is_hoyo = contains_keyword(fandom, hoyoverse_keywords) or contains_keyword(other_fandom, hoyoverse_keywords)
    is_vtuber = contains_keyword(fandom, vtuber_keywords) or contains_keyword(other_fandom, vtuber_keywords)
    is_gacha = contains_keyword(fandom, gacha_keywords) or contains_keyword(other_fandom, gacha_keywords)
    is_vsynth = contains_keyword(fandom, vsynth_keywords) or contains_keyword(other_fandom, vsynth_keywords)
    is_orig = contains_keyword(fandom, original_keywords, is_exact_oc=True) or contains_keyword(other_fandom, original_keywords, is_exact_oc=True)

    is_other = not any([is_hoyo, is_vtuber, is_gacha, is_vsynth, is_orig])

    return pd.Series([
        is_hoyo, is_vtuber, is_gacha, is_vsynth, is_orig, is_other
    ], index=['Hoyoverse', 'Vtuber', 'Other Gacha', 'V-Synth', 'Original', 'Other (Niche)'])

df_cf[['Hoyoverse', 'Vtuber', 'Other Gacha', 'V-Synth', 'Original', 'Other (Niche)']] = df_cf.apply(categorize_booth, axis=1)

# df_cf[['name', 'fandom', 'other_fandom', 'Hoyoverse', 'Vtuber', 'Other Gacha', 'V-Synth', 'Original', 'Other (Niche)', 'CF_Version']].sample(20)

# Fandom Comparison DataFrame
summary_data_fandom = []
for cf_ver in [21, 22]:
    subset = df_cf[df_cf['CF_Version'] == cf_ver]
    total = len(subset)

    summary_data_fandom.append({
        'Event': f'CF{cf_ver}',
        'Total Booths': total,
        'Hoyoverse Count': subset['Hoyoverse'].sum(),
        'Vtuber Count': subset['Vtuber'].sum(),
        'Other Gacha Count': subset['Other Gacha'].sum(),
        'V-Synth Count': subset['V-Synth'].sum(),
        'Original Count': subset['Original'].sum(),
        'Other (Niche) Count': subset['Other (Niche)'].sum(),

        'Hoyoverse %': subset['Hoyoverse'].sum() / total * 100,
        'Vtuber %': subset['Vtuber'].sum() / total * 100,
        'Other Gacha %': subset['Other Gacha'].sum() / total * 100,
        'V-Synth %': subset['V-Synth'].sum() / total * 100,
        'Original %': subset['Original'].sum() / total * 100,
        'Other (Niche) %': subset['Other (Niche)'].sum() / total * 100,
    })

df_summary_fandom = pd.DataFrame(summary_data_fandom)
df_summary_fandom.set_index('Event', inplace=True)

print("\n--- Fandom Comparison Summary ---")
pd.set_option('display.max_columns', None)
df_summary_fandom

# Plotting the lines of fandom trending in percent
events = df_summary_fandom.index.tolist()

categories = {
    'Hoyoverse': df_summary_fandom['Hoyoverse %'].tolist(),
    'Vtuber': df_summary_fandom['Vtuber %'].tolist(),
    'Other Gacha': df_summary_fandom['Other Gacha %'].tolist(),
    'V-Synth': df_summary_fandom['V-Synth %'].tolist(),
    'Original': df_summary_fandom['Original %'].tolist(),
    'Other (Niche)': df_summary_fandom['Other (Niche) %'].tolist()
}

plt.figure(figsize=(14, 9))

styles = {
    'Hoyoverse': {'marker': 'o', 'color': '#3b82f6'},
    'Vtuber': {'marker': 's', 'color': '#8b5cf6'},
    'Other Gacha': {'marker': 'D', 'color': '#f59e0b'},
    'V-Synth': {'marker': 'p', 'color': '#2dd4bf'},
    'Original': {'marker': 'h', 'color': '#db2777'},
    'Other (Niche)': {'marker': 'X', 'color': '#64748b'}
}

for label, values in categories.items():
    plt.plot(events, values, label=label, linewidth=3, marker=styles[label]['marker'], color=styles[label]['color'])

    for i, val in enumerate(values):
        offset = 8 if i == 0 else 8
        plt.annotate(f'{val:.1f}%',
                     (events[i], val),
                     textcoords='offset points',
                     xytext=(15 if i == 0 else -15, 0),
                     ha='left' if i == 0 else 'right',
                     va='center',
                     fontsize=10,
                     fontweight='bold',
                     bbox=dict(boxstyle='round,pad=0.2', fc='white', alpha=0.6, ec='none'))

plt.title('Market Share Comparison: All Fandom Categories (CF21 vs CF22)', fontsize=16, pad=20)
plt.xlabel('Event', fontsize=12)
plt.ylabel('Percentage of Total Booths (%)', fontsize=12)
plt.ylim(0, max([max(v) for v in categories.values()]) + 10)
plt.legend(title='Fandom Categories', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()

plt.show()

# Plotting the lines of fandom trending in booth count
plt.figure(figsize=(14, 9))

categories_count = {
    'Hoyoverse': df_summary_fandom['Hoyoverse Count'],
    'Vtuber': df_summary_fandom['Vtuber Count'],
    'Other Gacha': df_summary_fandom['Other Gacha Count'],
    'V-Synth': df_summary_fandom['V-Synth Count'],
    'Original': df_summary_fandom['Original Count'],
    'Other (Niche)': df_summary_fandom['Other (Niche) Count']
}

for label, values in categories_count.items():
    plt.plot(events, values, label=label, linewidth=3, marker=styles[label]['marker'], color=styles[label]['color'])
    for i, val in enumerate(values):
        plt.annotate(f'{int(val)}', (events[i], val), textcoords='offset points', xytext=(15 if i == 0 else -15, 0),
                     ha='left' if i == 0 else 'right', va='center', fontweight='bold', bbox=dict(boxstyle='round', fc='white', alpha=0.6))

plt.title('Booth Count Comparison: All Fandom Categories (CF21 vs CF22)', fontsize=16, pad=20)
plt.ylabel('Number of Booths')
plt.ylim(0, 750)
plt.legend(title='Fandom Categories', bbox_to_anchor=(1.05, 1))
plt.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

"""# Other Exploratory Data Analysis (EDA)"""

df_cf.info()

"""## Circle Booth Type, Rating, Day"""

df_cf.groupby(['CF_Version', 'circle_type']).size().unstack(fill_value=0)

df_cf.groupby(['CF_Version', 'rating']).size().unstack(fill_value=0)

df_cf.groupby(['CF_Version', 'day']).size().unstack(fill_value=0)

for col in ['circle_type', 'rating', 'day']:
    print(f'\n--- Percentage Distribution: {col} ---')
    # Group by event and column, then unstack to table
    counts = df_cf.groupby(['CF_Version', col]).size().unstack(fill_value=0)
    # Calculate percentage (row sum is the total booths for that event)
    percentages = counts.div(counts.sum(axis=1), axis=0) * 100
    display(percentages.round(2).astype(str) + '%')

"""## Provided Link (Social Media, etc.)"""

link_cols = ['circle_facebook', 'circle_instagram', 'circle_twitter', 'circle_other_socials', 'marketplace_link']
fig, axes = plt.subplots(2, 1, figsize=(12, 12))

for i, cf_ver in enumerate([21, 22]):
    subset = df_cf[df_cf['CF_Version'] == cf_ver]
    # Calculate counts and sort descending
    counts = subset[link_cols].notnull().sum().sort_values(ascending=True)

    counts.plot(kind='barh', ax=axes[i], color='#3b82f6' if cf_ver == 22 else '#94a3b8')
    axes[i].set_title(f'Count of Circles Providing Specific Links (CF{cf_ver})', fontsize=14)
    axes[i].set_xlabel('Number of Circles')
    axes[i].set_xlim(0, 1400)

    # Add labels on the right
    for container in axes[i].containers:
        axes[i].bar_label(container, padding=5, fontweight='bold')

plt.tight_layout()
plt.show()

"""## What They Sell"""

sells_cols = [col for col in df_cf.columns if col.startswith('Sells')]
subset_22 = df_cf[df_cf['CF_Version'] == 22]

# Calculate grid size for subplots
n_cols = 3
n_rows = (len(sells_cols) + n_cols - 1) // n_cols

fig, axes = plt.subplots(n_rows, n_cols, figsize=(18, 4 * n_rows))
axes = axes.flatten()

for i, col in enumerate(sells_cols):
    counts = subset_22[col].value_counts().sort_index(ascending=True) # False, then True

    # Map True/False to more readable labels
    counts.index = counts.index.map({True: 'Selling', False: 'Not Selling'})

    counts.plot(kind='bar', ax=axes[i], color=['#94a3b8', '#3b82f6'])
    axes[i].set_title(f'Distribution: {col}', fontsize=12)
    axes[i].set_ylabel('Count')
    axes[i].tick_params(axis='x', rotation=0)

    # Add labels on top
    for container in axes[i].containers:
        axes[i].bar_label(container, padding=3, fontweight='bold')

# Remove empty subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.suptitle('Product Category Participation (True vs False) - CF22', fontsize=20, y=1.02)
plt.tight_layout()
plt.show()

sells_cols = [col for col in df_cf.columns if col.startswith('Sells')]
subset_21 = df_cf[df_cf['CF_Version'] == 21]

# Calculate grid size for subplots
n_cols = 3
n_rows = (len(sells_cols) + n_cols - 1) // n_cols

fig, axes = plt.subplots(n_rows, n_cols, figsize=(18, 4 * n_rows))
axes = axes.flatten()

for i, col in enumerate(sells_cols):
    counts = subset_21[col].value_counts().sort_index(ascending=True) # False, then True

    # Map True/False to more readable labels
    counts.index = counts.index.map({True: 'Selling', False: 'Not Selling'})

    counts.plot(kind='bar', ax=axes[i], color=['#94a3b8', '#3b82f6'])
    axes[i].set_title(f'Distribution: {col} (CF21)', fontsize=12)
    axes[i].set_ylabel('Count')
    axes[i].tick_params(axis='x', rotation=0)

    # Add labels on top
    for container in axes[i].containers:
        axes[i].bar_label(container, padding=3, fontweight='bold')

# Remove empty subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.suptitle('Product Category Participation (True vs False) - CF21', fontsize=20, y=1.02)
plt.tight_layout()
plt.show()

"""# Export"""

# Export the combined and processed dataframe into a pickle file
joblib.dump(df_cf, 'df_cf.pkl')

print("Successfully exported df_cf to 'df_cf.pkl' using joblib.")