# -*- coding: utf-8 -*-
"""02A_Recommendation_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FSVrTMs0OhXVSpFLACeMUH8QH5SIiTmH

# Import and Load
"""

import pandas as pd
import numpy as np
import joblib
from scipy.spatial.distance import cdist

df_cf = joblib.load('df_cf.pkl')

df_cf.info()

"""# Preprocessing"""

# Select specific columns
sells_cols = [col for col in df_cf.columns if col.startswith('Sells')]
last_6_cols = df_cf.columns[-6:].tolist()
other_cols = ['name', 'CF_Version', 'rating', 'day', 'circle_type']

# Combine and remove potential duplicates while preserving order
selected_columns = []
for col in (other_cols + sells_cols + last_6_cols):
    if col in df_cf.columns and col not in selected_columns:
        selected_columns.append(col)

# Create the new dataframe
df_recommendation = df_cf[selected_columns].copy()

# Display info to verify
df_recommendation.info()

# Perform One-Hot Encoding for the specified columns
# pd.get_dummies automatically drops the original columns and replaces them with dummies
df_recommendation = pd.get_dummies(df_recommendation, columns=['rating', 'day', 'circle_type'], prefix=['rating', 'day', 'circle_type'])

# Display the new columns to verify
print(df_recommendation.columns.tolist())

# Split the dataframe based on CF_Version
df_recommendation_21 = df_recommendation[df_recommendation['CF_Version'] == 21].copy()
df_recommendation_22 = df_recommendation[df_recommendation['CF_Version'] == 22].copy()

# Drop CF_Version column from the new dataframes
df_recommendation_21.drop(columns=['CF_Version'], inplace=True)
df_recommendation_22.drop(columns=['CF_Version'], inplace=True)

# Verify the split
print(f"df_recommendation_21 shape: {df_recommendation_21.shape}")
print(f"df_recommendation_22 shape: {df_recommendation_22.shape}")

"""# Recommendation Modeling"""

def get_recommendations(target_name, df, top_n=10):
    """
    General recommendation function that works on a provided DataFrame.
    """
    if target_name not in df['name'].values:
        return f"Name '{target_name}' not found in the provided DataFrame."

    # Isolate target features and candidate features
    target_row = df[df['name'] == target_name].drop(columns=['name'])
    candidates = df[df['name'] != target_name].copy()
    candidate_features = candidates.drop(columns=['name'])

    # Calculate Jaccard distance from 1 to many
    distances = cdist(target_row.values, candidate_features.values, metric='jaccard').flatten()

    # Add results to candidates dataframe
    candidates['distance'] = distances

    # Return top N results sorted by distance
    return candidates[['name', 'distance']].sort_values(by='distance').head(top_n)

# Example usage for CF_Version 21
first_name_21 = df_recommendation_21['name'].iloc[0]
print(f"Recommendations for {first_name_21} (from df_recommendation_21):")
print(get_recommendations(first_name_21, df_recommendation_21))

print("\n" + "="*50 + "\n")

# Example usage for CF_Version 22
first_name_22 = df_recommendation_22['name'].iloc[0]
print(f"Recommendations for {first_name_22} (from df_recommendation_22):")
print(get_recommendations(first_name_22, df_recommendation_22))

"""# Export Pipeline"""

class CircleRecommender:
    def __init__(self):
        pass

    def prepare_raw_data(self, df_raw):
        """
        Preprocesses the raw df_cf data into the encoded format.
        Returns both dataframes for version 21 and 22 separately.
        """
        sells_cols = [col for col in df_raw.columns if col.startswith('Sells')]
        last_6_cols = df_raw.columns[-6:].tolist()
        other_cols = ['name', 'circle_code', 'CF_Version', 'rating', 'day', 'circle_type']

        selected_columns = []
        for col in (other_cols + sells_cols + last_6_cols):
            if col in df_raw.columns and col not in selected_columns:
                selected_columns.append(col)

        df = df_raw[selected_columns].copy()

        # One-Hot Encoding
        df = pd.get_dummies(df, columns=['rating', 'day', 'circle_type'],
                            prefix=['rating', 'day', 'circle_type'])

        # Split by CF_Version and drop version column
        df_21 = df[df['CF_Version'] == 21].drop(columns=['CF_Version']).copy()
        df_22 = df[df['CF_Version'] == 22].drop(columns=['CF_Version']).copy()

        return df_21, df_22

    def get_recommendations(self, identifier, df_version, top_n=10):
        """
        Assumes df_version is the already split/filtered dataframe for a specific CF.
        identifier: can be 'name' or 'circle_code'
        """
        # Find the target row
        mask = (df_version['name'] == identifier) | (df_version['circle_code'] == identifier)
        target_data = df_version[mask]

        if target_data.empty:
            return f"'{identifier}' not found in the provided dataset."

        # Use first match if multiple found within same DF
        target_name = target_data.iloc[0]['name']

        # Drop metadata for distance calculation
        target_features = target_data.iloc[[0]].drop(columns=['name', 'circle_code'])
        candidates = df_version[df_version['name'] != target_name].copy()
        candidate_features = candidates.drop(columns=['name', 'circle_code'])

        # Calculate distances
        distances = cdist(target_features.values, candidate_features.values, metric='jaccard').flatten()
        candidates['distance'] = distances

        return candidates[['circle_code', 'name', 'distance']].sort_values('distance').head(top_n)

# Initialize
recommender = CircleRecommender()

# Preprocess in environment (simulating production flow)
df_rec_21, df_rec_22 = recommender.prepare_raw_data(df_cf)

# Export only the model for production
joblib.dump(recommender, 'recommender_pipeline.pkl')

print("CircleRecommender model exported to 'recommender_pipeline.pkl'")

# Demo check using the split dataframes
print("\nDemo Recommendation (CF 21) for 'AA-01':")
print(recommender.get_recommendations('AA-01', df_rec_21, top_n=5))