# -*- coding: utf-8 -*-
"""02B_Faktor_Rating_Part_1.ipynb

Automatically generated by Colab.

# Import, Load, Preprocessing
"""

# !pip install imblearn xgboost

import pandas as pd
import numpy as np
import joblib

from imblearn.combine import SMOTETomek

from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.utils.class_weight import compute_sample_weight

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
from matplotlib import rcParams

rcParams['figure.figsize'] = 15, 8
mpl.style.use(['ggplot'])

df_cf = joblib.load('df_cf.pkl')

# Drop rows where 'rating' is NaN
df_cf = df_cf.dropna(subset=['rating'])

print(f"New shape of df_cf: {df_cf.shape}")

# Define X: all columns starting with 'Sells' and the last 6 columns
sells_columns = [col for col in df_cf.columns if col.startswith('Sells')]
last_6_columns = df_cf.columns[-6:].tolist()

# Combine lists and remove duplicates while preserving order
combined_columns = sells_columns + last_6_columns
X_columns = []
for col in combined_columns:
    if col not in X_columns:
        X_columns.append(col)

X = df_cf[X_columns]

# Define y
y = df_cf['rating']

print(f"Shape of X: {X.shape}")
print(f"Shape y: {y.shape}")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=30)

# Calculate the correlation matrix for X
corr_matrix = X.corr()

# Visualize using a Seaborn heatmap
plt.figure(figsize=(14, 10))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap='RdBu', center=0)
plt.title('Correlation Matrix of Features (X)')
plt.show()

"""# Feature Selection"""

chi_scores, p_values = chi2(X_train, y_train)

df_selection = pd.DataFrame({'Feature': X_train.columns, 'Chi-Square Score': chi_scores, 'P-Value': p_values})

df_selection = df_selection.sort_values(by='Chi-Square Score', ascending=False).reset_index(drop=True)
df_selection

df_selection['Signifikansi'] = np.where(df_selection['P-Value'] < 0.05, 'Signifikan', 'Tidak Signifikan')

plt.figure(figsize=(10, 8))
sns.barplot(x='Chi-Square Score', y='Feature' , data=df_selection, hue='Signifikansi', dodge=False, palette='magma')
plt.title("Uji Signifikansi menggunakan Chi-Square")
plt.xlabel("Skor Chi Square")
plt.ylabel("Fitur")
plt.legend()
plt.tight_layout()
plt.show()

significant_features = df_selection[df_selection['Signifikansi'] == 'Signifikan']['Feature'].tolist()
print("Significant Features:", significant_features)

"""# Sampling"""

# Convert boolean columns to int to avoid TypeError during resampling
X_numeric = X_train.astype(int)

# Initialize SMOTETomek
smt = SMOTETomek(random_state=42)

# Fit and resample X and y
X_res, y_res = smt.fit_resample(X_numeric, y_train)

# print("--- Value Counts for y (Resampled) ---")
# print(y_res.value_counts())

# print("\n--- Value Counts for each column in X (Resampled) ---")
# for col in X_res.columns:
#     print(f"\nFeature: {col}")
#     print(X_res[col].value_counts())

"""# Naive Bayes"""

def custom_penalty_score(y_true, y_pred, labels, cost_matrix):
    """
    Calculates a mean penalty score based on a custom cost matrix.
    The score is normalized by the number of samples to allow
    comparison between different set sizes (e.g., train vs test).
    Lower scores are better.
    """
    from sklearn.metrics import confusion_matrix

    cm = confusion_matrix(y_true, y_pred, labels=labels)
    # Multiply the confusion matrix by the cost matrix element-wise
    weighted_penalties = cm * cost_matrix
    total_penalty = np.sum(weighted_penalties)

    # Normalize by total number of samples
    mean_penalty = total_penalty / len(y_true)

    return mean_penalty, cm

# Define your labels in the specific order they appear in the matrix
labels = ['GA', 'M', 'PG']

# Define your cost matrix (Rows = Actual, Cols = Predicted)
costs = np.array([
    [0, 16, 1],   # Actual GA
    [20, 0, 12],  # Actual M
    [2, 8, 0]     # Actual PG
])

# Note: ensure y_pred is defined from your model before running this
# penalty, cm_result = custom_penalty_score(y_test, y_pred, labels, costs)
# print(f"Mean Custom Penalty Score: {penalty:.4f}")

# Initialize models
alpha = 1.0
class_prior = [0.33, 0.33, 0.33]

bnb_1 = BernoulliNB(alpha=alpha, class_prior=class_prior) # NB Default
bnb_2 = BernoulliNB(alpha=alpha, class_prior=class_prior) # NB Selected Feature
bnb_3 = BernoulliNB(alpha=alpha) # NB Sampled
bnb_4 = BernoulliNB(alpha=alpha) # NB Sampled + Selected Feature

# Train models
bnb_1.fit(X_train, y_train)
bnb_2.fit(X_train[significant_features], y_train)
bnb_3.fit(X_res, y_res)
bnb_4.fit(X_res[significant_features], y_res)

# Scenarios setup for evaluation loop
nb_scenarios = [
    ("NB Default", bnb_1, X_test),
    ("NB Selected Feature", bnb_2, X_test[significant_features]),
    ("NB Sampled", bnb_3, X_test),
    ("NB Sampled + Selected Feature", bnb_4, X_test[significant_features])
]

performance_results = []

for name, model, test_data in nb_scenarios:
    preds = model.predict(test_data)

    # Calculate requested metrics
    acc = accuracy_score(y_test, preds)
    f1_w = f1_score(y_test, preds, average='weighted')
    f1_m = f1_score(y_test, preds, average='macro')
    # Using the updated mean penalty function from the previous cell
    penalty_val, _ = custom_penalty_score(y_test, preds, labels, costs)

    performance_results.append({
        "Model": name,
        "Accuracy": acc,
        "F1 Weighted": f1_w,
        "F1 Macro": f1_m,
        "Penalty Score": penalty_val
    })

# Create the final performance DataFrame
df_models_performance = pd.DataFrame(performance_results).set_index("Model")

df_models_performance

# Get predictions for the specific model (bnb_4)
y_pred_bnb4 = bnb_4.predict(X_test[significant_features])

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred_bnb4, labels=labels)

# Visualization
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels)
plt.title('Confusion Matrix: NB Sampled + Selected Feature')
plt.xlabel('Predicted Label')
plt.ylabel('Actual Label')
plt.show()

"""# Random Forest"""

# Initialize RF models
# For models without resampling (X_train), we use class_weight='balanced'
rf_1 = RandomForestClassifier(random_state=42, class_weight='balanced') # RF Default
rf_2 = RandomForestClassifier(random_state=42, class_weight='balanced') # RF Selected Feature
rf_3 = RandomForestClassifier(random_state=42) # RF Sampled (X_res is already balanced)
rf_4 = RandomForestClassifier(random_state=42) # RF Sampled + Selected Feature

# Train RF models
rf_1.fit(X_train, y_train)
rf_2.fit(X_train[significant_features], y_train)
rf_3.fit(X_res, y_res)
rf_4.fit(X_res[significant_features], y_res)

# Scenarios setup for RF
rf_scenarios = [
    ("RF Default", rf_1, X_test),
    ("RF Selected Feature", rf_2, X_test[significant_features]),
    ("RF Sampled", rf_3, X_test),
    ("RF Sampled + Selected Feature", rf_4, X_test[significant_features])
]

rf_results = []

for name, model, test_data in rf_scenarios:
    preds = model.predict(test_data)

    acc = accuracy_score(y_test, preds)
    f1_w = f1_score(y_test, preds, average='weighted')
    f1_m = f1_score(y_test, preds, average='macro')
    penalty_val, _ = custom_penalty_score(y_test, preds, labels, costs)

    rf_results.append({
        "Model": name,
        "Accuracy": acc,
        "F1 Weighted": f1_w,
        "F1 Macro": f1_m,
        "Penalty Score": penalty_val
    })

# Append RF results to the existing NB performance dataframe
df_rf_performance = pd.DataFrame(rf_results).set_index("Model")
df_models_performance = pd.concat([df_models_performance, df_rf_performance])

# Display updated dataframe sorted by Accuracy
df_models_performance.sort_values(by="Penalty Score", ascending=True)

# Get predictions for the specific model (rf_1)
y_pred_rf1 = rf_1.predict(X_test)

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred_rf1, labels=labels)

# Visualization
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels)
plt.title('Confusion Matrix: RF Default')
plt.xlabel('Predicted Label')
plt.ylabel('Actual Label')
plt.show()

"""# Logistic Regression"""

# Initialize Logistic Regression models
# Scenario 1: Default (Imbalanced, All Features) -> L1 Regularization, Balanced weights
lr_1 = LogisticRegression(penalty='l1', solver='liblinear', class_weight='balanced', random_state=42)
# Scenario 2: Selected Features (Imbalanced) -> Default L2, Balanced weights
lr_2 = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)
# Scenario 3: Sampled (Balanced via SMOTE-Tomek, All Features) -> L1 Regularization
lr_3 = LogisticRegression(penalty='l1', solver='liblinear', random_state=42)
# Scenario 4: Sampled + Selected Feature -> Default L2
lr_4 = LogisticRegression(random_state=42, max_iter=1000)

# Train LR models
lr_1.fit(X_train, y_train)
lr_2.fit(X_train[significant_features], y_train)
lr_3.fit(X_res, y_res)
lr_4.fit(X_res[significant_features], y_res)

# Scenarios setup for LR evaluation
lr_scenarios = [
    ("LR Default (L1)", lr_1, X_test),
    ("LR Selected Feature", lr_2, X_test[significant_features]),
    ("LR Sampled (L1)", lr_3, X_test),
    ("LR Sampled + Selected Feature", lr_4, X_test[significant_features])
]

lr_results = []

for name, model, test_data in lr_scenarios:
    preds = model.predict(test_data)

    acc = accuracy_score(y_test, preds)
    f1_w = f1_score(y_test, preds, average='weighted')
    f1_m = f1_score(y_test, preds, average='macro')
    penalty_val, _ = custom_penalty_score(y_test, preds, labels, costs)

    lr_results.append({
        "Model": name,
        "Accuracy": acc,
        "F1 Weighted": f1_w,
        "F1 Macro": f1_m,
        "Penalty Score": penalty_val
    })

# Append LR results to the existing performance dataframe
df_lr_performance = pd.DataFrame(lr_results).set_index("Model")
df_models_performance = pd.concat([df_models_performance, df_lr_performance])

df_models_performance.sort_values(by="Penalty Score", ascending=True)

"""# XGBoost"""

# XGBoost requires labels to be integers [0, 1, 2]
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)
y_res_enc = le.transform(y_res)

# Calculate sample weights for imbalanced training sets
sample_weights_train = compute_sample_weight(class_weight='balanced', y=y_train)

# Initialize XGB models
xgb_1 = XGBClassifier(random_state=42) # XGB Default
xgb_2 = XGBClassifier(random_state=42) # XGB Selected Feature
xgb_3 = XGBClassifier(random_state=42) # XGB Sampled
xgb_4 = XGBClassifier(random_state=42) # XGB Sampled + Selected Feature

# Train XGB models
# Use sample weights for imbalanced data (1 and 2)
xgb_1.fit(X_train, y_train_enc, sample_weight=sample_weights_train)
xgb_2.fit(X_train[significant_features], y_train_enc, sample_weight=sample_weights_train)
# Resampled data (3 and 4) is already balanced, so no sample_weight needed
xgb_3.fit(X_res, y_res_enc)
xgb_4.fit(X_res[significant_features], y_res_enc)

# Scenarios setup for XGB evaluation
xgb_scenarios = [
    ("XGB Default", xgb_1, X_test),
    ("XGB Selected Feature", xgb_2, X_test[significant_features]),
    ("XGB Sampled", xgb_3, X_test),
    ("XGB Sampled + Selected Feature", xgb_4, X_test[significant_features])
]

xgb_results = []

for name, model, test_data in xgb_scenarios:
    preds_enc = model.predict(test_data)
    preds = le.inverse_transform(preds_enc)

    acc = accuracy_score(y_test, preds)
    f1_w = f1_score(y_test, preds, average='weighted')
    f1_m = f1_score(y_test, preds, average='macro')
    penalty_val, _ = custom_penalty_score(y_test, preds, labels, costs)

    xgb_results.append({
        "Model": name,
        "Accuracy": acc,
        "F1 Weighted": f1_w,
        "F1 Macro": f1_m,
        "Penalty Score": penalty_val
    })

# Append XGB results to the existing performance dataframe
df_xgb_performance = pd.DataFrame(xgb_results).set_index("Model")
df_models_performance = pd.concat([df_models_performance[~df_models_performance.index.str.startswith('XGB')], df_xgb_performance])

# Display final updated dataframe sorted by Penalty Score
df_models_performance.sort_values(by="Penalty Score", ascending=True)

"""# Export"""

# Extract feature importances from the rf_1 model
importances = rf_1.feature_importances_
feature_names = X_train.columns

# Create a DataFrame for visualization
df_importance = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
df_importance = df_importance.sort_values(by='Importance', ascending=False)

# Plotting using Seaborn - Updated to fix FutureWarning
plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=df_importance, hue='Feature', palette='viridis', legend=False)

plt.title('Feature Importance: Random Forest Default (rf_1)')
plt.xlabel('Importance Score')
plt.ylabel('Features')
plt.tight_layout()
plt.show()

# Export the feature importance DataFrame
joblib.dump(df_importance, 'df_importance_rating.pkl')

# Bundle the datasets into a dictionary for easy export
data_to_export = {
    'X_train': X_train,
    'X_test': X_test,
    'y_train': y_train,
    'y_test': y_test
}

# Export using joblib
joblib.dump(data_to_export, 'rating_data_split.pkl')

print("Datasets exported successfully to 'rating_data_split.pkl'")

# --- HOW TO CALL IT LATER ---
# To load these back in a different session, use the following code:
#
# import joblib
# loaded_data = joblib.load('rating_data_split.pkl')
# X_train = loaded_data['X_train']
# X_test = loaded_data['X_test']
# y_train = loaded_data['y_train']
# y_test = loaded_data['y_test']