# -*- coding: utf-8 -*-
"""02C_Faktor_Tipe_Part_2.ipynb

Automatically generated by Colab.

# Awal
"""

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, make_scorer, f1_score, accuracy_score, balanced_accuracy_score

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
from matplotlib import rcParams

rcParams['figure.figsize'] = 15, 8
mpl.style.use(['ggplot'])

df_split = joblib.load("circle_type_data_split.pkl")

X_train = df_split['X_train']
X_test = df_split['X_test']
y_train = df_split['y_train']
y_test = df_split['y_test']

"""Custom Penalty Score dengan matriks yang juga bisa digunakan dengan tools Sklearn yang lain (cross_val, GridSearch, dsb.)"""

def custom_penalty_score(y_true, y_pred, labels, cost_matrix):
    """
    Calculates a mean penalty score based on a custom cost matrix.
    Lower scores are better.
    """
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    # Multiply the confusion matrix by the cost matrix element-wise
    weighted_penalties = cm * cost_matrix
    total_penalty = np.sum(weighted_penalties)

    # Normalize by total number of samples
    mean_penalty = total_penalty / len(y_true)

    return mean_penalty

# Define your labels and cost matrix
labels = ['1 Space(s)', '2 Space(s)', '4 Space(s)', 'Booth_A', 'Booth_B']
costs = np.array([
    [0, 4, 8, 12, 16],   # Actual 1 Space(s)
    [4, 0, 6, 10, 14],   # Actual 2 Space(s)
    [8, 4, 0, 2, 11],   # Actual 4 Space(s)
    [14, 8, 2, 0, 4], # Actual Booth_A
    [20, 14, 8, 4, 0]  # Actual Booth_B
])

# Create the scorer for sklearn
# greater_is_better=False because we want to minimize the penalty
penalty_scorer = make_scorer(
    custom_penalty_score,
    greater_is_better=False,
    labels=labels,
    cost_matrix=costs
)

print("Scorer 'penalty_scorer' is ready for use in GridSearchCV or cross_val_score.")

# Initialize model
lr_non_tuned = joblib.load('lr_non_tuned.pkl')

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Run cross-validation with custom penalty scorer
# Note: because greater_is_better=False, sklearn returns negative values
rf_penalty_scores = cross_val_score(lr_non_tuned, X_train, y_train, scoring=penalty_scorer, cv=skf)

# Convert to positive penalty values for easier reading
actual_penalties = np.abs(rf_penalty_scores)

print("Custom Penalty per Fold = ", actual_penalties)
print("Average Penalty = ", actual_penalties.mean())
print("Penalty Std Dev = ", actual_penalties.std())

"""# Hyperparameter Tuning

Sudah uji coba beberapa scoring, dan f1 macro yang paling baik
"""

lr_f1_scores = cross_val_score(lr_non_tuned, X_train, y_train, scoring='f1_macro', cv=skf)

print("F1 Macro per Fold = ", lr_f1_scores)
print("Average F1 Macro = ", lr_f1_scores.mean())
print("F1 Macro Std Dev = ", lr_f1_scores.std())

parameters_lr = {
    'C': [0.01, 0.1, 1, 10, 100],      # Default = 1
    'solver': ['liblinear', 'saga'],   # Default = 'lbfgs', but for L1 the default = 'liblinear'
    'max_iter': [100, 500, 1000]       # Default = 100
}

"""Sekitar 1 menit"""

search_lr = GridSearchCV(
    estimator=lr_non_tuned,
    param_grid=parameters_lr,
    cv=skf,
    scoring='f1_macro',
    verbose=3,
)

search_lr.fit(X_train, y_train)

print("Best Parameters:", search_lr.best_params_)
print("Best Score:", search_lr.best_score_)
print("Actual Best Penalty Score:", abs(search_lr.best_score_))

# Note: Scores are negative because GridSearchCV maximizes.
# A score of -1.74 is better (higher) than -2.00.

lr_tuned = search_lr.best_estimator_

lr_tuned_cv = cross_val_score(lr_tuned, X_train, y_train, cv=skf, scoring="f1_macro")
print("F1 Macro masing-masing = ", lr_tuned_cv)
print("Rata-rata F1 Macro = ", lr_tuned_cv.mean())
print("Simpangan baku F1 Macro = ", lr_tuned_cv.std())

"""# Evaluasi

Data Train
"""

# Predict on the training set
y_pred_train = lr_tuned.predict(X_train)

# Calculate Metrics
train_accuracy = accuracy_score(y_train, y_pred_train)
train_balanced_accuracy = balanced_accuracy_score(y_train, y_pred_train)
train_f1_weighted = f1_score(y_train, y_pred_train, average='weighted')
train_f1_macro = f1_score(y_train, y_pred_train, average='macro')
train_penalty = custom_penalty_score(y_train, y_pred_train, labels=labels, cost_matrix=costs)

print(f"--- Training Performance ---")
print(f"Accuracy: {train_accuracy:.4f}")
print(f"Balanced Accuracy: {train_balanced_accuracy:.4f}")
print(f"F1 Weighted: {train_f1_weighted:.4f}")
print(f"F1 Macro: {train_f1_macro:.4f}")
print(f"Penalty Score: {train_penalty:.4f}")

# Confusion Matrix
cm_train = confusion_matrix(y_train, y_pred_train, labels=labels)

plt.figure(figsize=(10, 7))
sns.heatmap(cm_train, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Tuned Logistic Regression (Training Set)')
plt.show()

"""Data Test"""

# Predict on the test set
y_pred_test = lr_tuned.predict(X_test)

# Calculate Metrics
test_accuracy = accuracy_score(y_test, y_pred_test)
test_balanaced_accuracy = balanced_accuracy_score(y_test, y_pred_test)
test_f1_weighted = f1_score(y_test, y_pred_test, average='weighted')
test_f1_macro = f1_score(y_test, y_pred_test, average='macro')
test_penalty = custom_penalty_score(y_test, y_pred_test, labels=labels, cost_matrix=costs)

print(f"--- Test Performance ---")
print(f"Accuracy: {test_accuracy:.4f}")
print(f"Balanced Accuracy: {test_balanaced_accuracy:.4f}")
print(f"F1 Weighted: {test_f1_weighted:.4f}")
print(f"F1 Macro: {test_f1_macro:.4f}")
print(f"Penalty Score: {test_penalty:.4f}")

# Confusion Matrix
cm_test = confusion_matrix(y_test, y_pred_test, labels=labels)

plt.figure(figsize=(10, 7))
sns.heatmap(cm_test, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Tuned Logistic Regression (Test Set)')
plt.show()

"""K-Fold dengan menyatukan Data Train dan Test"""

# 1. Combine the training and testing data
X_full = pd.concat([X_train, X_test], axis=0)
y_full = pd.concat([y_train, y_test], axis=0)

print(f"Combined Dataset Shape: {X_full.shape}")

# 2. Perform Stratified K-Fold CV for F1 Macro
f1_cv_scores = cross_val_score(
    lr_tuned,
    X_full,
    y_full,
    cv=skf,
    scoring='f1_macro'
)

# 3. Perform Stratified K-Fold CV for Penalty Score
penalty_cv_scores = cross_val_score(
    lr_tuned,
    X_full,
    y_full,
    cv=skf,
    scoring=penalty_scorer
)

# 4. Process and display results
actual_penalties = np.abs(penalty_cv_scores)

print("\n--- General Stratified K-Fold CV Results (Full Dataset) ---")
print(f"Average F1 Macro: {f1_cv_scores.mean():.4f} (+/- {f1_cv_scores.std():.4f})")
print(f"Average Penalty: {actual_penalties.mean():.4f} (+/- {actual_penalties.std():.4f})")

print("\nF1 Macro per fold:", f1_cv_scores)
print("Penalty per fold:", actual_penalties)

"""# Export"""

# Export the tuned model
model_filename = 'prediksi_type_pipeline.pkl'
joblib.dump(lr_tuned, model_filename)
print(f"Model successfully exported to {model_filename}")

# --- How to use this pkl later ---
# # Load the model
# loaded_model = joblib.load('rf_tuned_model.pkl')
#
# # To predict classes:
# # predictions = loaded_model.predict(X_new)
#
# # To predict probabilities:
# # probabilities = loaded_model.predict_proba(X_new)